<?php
$siteName = "Climate Change Club";
$pageTitle = "Why Stop Climate Change? | Climate Change Club";
$pageDescription = "Understand the real-world reasons climate change matters, from health and extreme weather to food, nature, and a fairer future.";
include "includes/header.php";
?>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Can individual actions really help?","acceptedAnswer":{"@type":"Answer","text":"Yes, especially when individual actions become shared habits and support better systems."}},{"@type":"Question","name":"What makes an action high impact?","acceptedAnswer":{"@type":"Answer","text":"Actions that reduce fossil-fuel use, protect nature, improve resilience, or help more people participate are strong places to start."}},{"@type":"Question","name":"Where should I begin?","acceptedAnswer":{"@type":"Answer","text":"Pick one area you care about, such as energy, transport, food, nature, or community education, and choose one sustainable next step."}}]}
</script>
<main id="main-content" class="reasons-page">
    <section class="page-hero compact-hero" aria-labelledby="reasons-title"><div><p class="eyebrow">The case for action</p><h1 id="reasons-title">Why climate action matters</h1><p>Climate change is not only an environmental issue. It affects the places we live, the air we breathe, the food we grow, and the opportunities available to future generations.</p></div></section>
    <section class="reason-grid" aria-label="Reasons to stop climate change">
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-heart-pulse"></i></span><h2>Protect human health</h2><p>Hotter days, wildfire smoke, floods, and changing disease patterns increase health risks. Cleaner energy and cooler, greener communities help people breathe easier and stay safer.</p><a href="https://www.who.int/news-room/fact-sheets/detail/climate-change-and-health" target="_blank" rel="noopener noreferrer">WHO: climate and health <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a></article>
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-house-chimney-crack"></i></span><h2>Reduce extreme weather risks</h2><p>Climate change loads the dice toward more intense heat, heavy rainfall, drought, and coastal flooding. Cutting emissions and preparing locally can reduce damage and protect homes.</p><a href="https://www.ipcc.ch/report/ar6/syr/" target="_blank" rel="noopener noreferrer">IPCC: synthesis report <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a></article>
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-seedling"></i></span><h2>Keep food and water secure</h2><p>Farms, fisheries, and water supplies depend on stable seasons and healthy ecosystems. Climate-smart choices protect harvests and make communities more resilient.</p><a href="https://www.fao.org/climate-change/en" target="_blank" rel="noopener noreferrer">FAO: climate and food <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a></article>
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-leaf"></i></span><h2>Give nature room to recover</h2><p>Plants and animals are already shifting their ranges as conditions change. Restoring forests, wetlands, and soil can store carbon while giving wildlife more room to adapt.</p><a href="https://www.ipcc.ch/report/ar6/wg2/" target="_blank" rel="noopener noreferrer">IPCC: impacts and adaptation <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a></article>
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-scale-balanced"></i></span><h2>Build a fairer future</h2><p>People who have contributed least to global emissions often face the greatest risks. A just transition means cleaner air, good jobs, reliable energy, and support for vulnerable communities.</p><a href="https://www.un.org/en/climatechange/what-is-climate-change" target="_blank" rel="noopener noreferrer">United Nations overview <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a></article>
        <article class="reason-card"><span class="reason-icon" aria-hidden="true"><i class="fas fa-bolt"></i></span><h2>Create better everyday systems</h2><p>Climate solutions can also mean quieter streets, efficient homes, renewable power, cleaner transport, and more resilient neighborhoods. Action is an investment in quality of life.</p><a href="projects.php">See our local projects <i class="fas fa-arrow-right" aria-hidden="true"></i></a></article>
    </section>
    <section class="reasons-cta" aria-labelledby="reasons-cta-title"><div><p class="eyebrow">Knowledge becomes momentum</p><h2 id="reasons-cta-title">Choose one useful next step</h2><p>You do not have to solve everything at once. Learn, join a project, or bring one idea to the club.</p></div><div class="hero-actions"><a class="btn-primary" href="projects.php">Explore projects</a><a class="btn-secondary" href="contact.php">Talk with the club</a></div></section>
    <section class="reasons-faq" aria-labelledby="faq-title"><p class="eyebrow">Quick answers</p><h2 id="faq-title">Common questions</h2><div class="faq-list"><details><summary>Can individual actions really help?</summary><p>Yes, especially when they become shared habits and support better systems. Personal choices can reduce demand, build community, and show leaders what people value.</p></details><details><summary>What makes an action high impact?</summary><p>Start with actions that reduce fossil-fuel use, protect nature, improve resilience, or help more people participate. The best action is one you can sustain and invite others into.</p></details><details><summary>Where should I begin?</summary><p>Pick one area you care about: energy, transport, food, nature, or community education. Our projects page turns those interests into practical ways to get involved.</p></details></div></section>
</main>
<?php include "includes/footer.php"; ?>
